day 3 in training

1-create array and print the arrey , shape and type

In [2]:
import numpy as np
randarr=np.arange(1,17).reshape(4,4)
print(randarr)
print(randarr.shape)
print(randarr.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)
int64


2=find the elemnt 

لم افهم كيف بدكم ياها فحليتها بطريقتين

In [6]:
subarr=randarr[3,2]
print(subarr)

15


2.1-second way

In [5]:
print(randarr[0:,1].reshape(4,1))
print(randarr[3])

[[ 2]
 [ 6]
 [10]
 [14]]
[13 14 15 16]


3-print the numbers greater than array mean

In [4]:
means=randarr.mean()
gt=randarr>means
print(randarr[gt])

[ 9 10 11 12 13 14 15 16]


4-create a row for add in random numbers between 1-20 with size 4 

 add it 


last thing is the check

In [3]:
addedrow=np.random.randint(1,20,size=4)
finalarr=randarr+addedrow
print(randarr)
print("**********************")
print(addedrow)
print("**********************")
print(finalarr)
check1=randarr[0,0]+addedrow[0]
print(f"""
      the number in the matrix[0,0]= {randarr[0,0]}
      the addnumber from the addrow (0)= {addedrow[0]}
       {randarr[0,0]} + {addedrow[0]} = {finalarr[0,0]} 
      """)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
**********************
[ 4 11  1 16]
**********************
[[ 5 13  4 20]
 [ 9 17  8 24]
 [13 21 12 28]
 [17 25 16 32]]

      the number in the matrix[0,0]= 1
      the addnumber from the addrow (0)= 4
       1 + 4 = 5 
      
